# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/360MoveData/Users/asus/Desktop/Computer_Program/COD-labs/Lab6/Lab6/Lab6.srcs/sources_1/ip/ROM_1/ROM.xci
# IP: The module: 'ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/360MoveData/Users/asus/Desktop/Computer_Program/COD-labs/Lab6/Lab6/Lab6.srcs/sources_1/ip/ROM_1/ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/360MoveData/Users/asus/Desktop/Computer_Program/COD-labs/Lab6/Lab6/Lab6.srcs/sources_1/ip/ROM_1/ROM.xci
# IP: The module: 'ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/360MoveData/Users/asus/Desktop/Computer_Program/COD-labs/Lab6/Lab6/Lab6.srcs/sources_1/ip/ROM_1/ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
